export const homepageContent = {
  brand: 'Northline Signal',
  nav: [
    { label: 'How it works', href: '#problem' },
    { label: 'Performance', href: '/performance' },
    { label: 'Methodology', href: '/methodology' },
    { label: 'Pricing', href: '/pricing' },
    { label: 'About', href: '/about' },
  ],
  hero: {
    eyebrow: '1. The Answer',
    headline: ['One question.', 'One answer.', 'Every day.'],
    body: 'System output: S&P 500 exposure signal. Updated daily. No discretion.',
    primaryCta: { label: 'View current signal', href: '/stocks/SPY' },
    secondaryCta: { label: 'See how it works', href: '#problem' },
    snapshot: {
      label: 'Current signal',
      status: 'Allocated',
      allocation: 80,
      caption: 'Current exposure view',
      confidence: 'High confidence',
      updatedAt: 'Updated Apr 24, 2026 10:15 AM ET',
      age: 'Signal age: 3 days',
      nextUpdate: 'Next update in ~6 hours',
    },
    proofs: [
      { title: 'Rule-based', body: 'No discretion' },
      { title: 'Live updates', body: 'Daily after market close' },
      { title: 'Transparent', body: 'See the logic' },
      { title: 'Consistent', body: 'Same process, every day' },
    ],
  },
  problem: {
    eyebrow: '2. The Problem',
    headline: 'Market timing is hard. Human nature makes it harder.',
    reasons: [
      {
        title: 'Emotions drive bad decisions.',
        body: 'Fear after drawdowns. Greed near tops.',
      },
      {
        title: "Forecasts don't stay accurate.",
        body: 'Most predictions fail when it matters most.',
      },
      {
        title: 'Exiting is the hardest part.',
        body: 'The hard part is knowing when to step aside.',
      },
      {
        title: 'Inconsistency compounds loss.',
        body: 'Small errors in timing create large gaps.',
      },
    ],
    callout:
      'Northline Signal removes emotion and guesswork, giving you a clear, systematic read on exposure.',
    calloutAside: 'Built for investors who want a system, not speculation.',
  },
  evidence: {
    eyebrow: '3. The Evidence',
    headline: 'A consistent process. Through every kind of market.',
    body: [
      'Northline Signal has been running live since January 2018.',
      'A systematic signal for market exposure, shown here on the S&P 500.',
      'The same rules are applied through every market regime.',
    ],
    processLine: 'Same process. Every day. No overrides.',
    stats: [
      { title: 'Live since', value: 'Jan 2018' },
      { title: 'Years running', value: '7+ years' },
      { title: 'Rule-based', value: 'No overrides' },
      { title: 'Update frequency', value: 'Daily after market close' },
    ],
    chart: {
      title: 'Model vs. Buy & Hold (S&P 500)',
      subtitle: 'Net of fees',
      modelReturn: '238%',
      buyHoldReturn: '112%',
      asOf: 'As of Apr 24, 2026',
      phases: [
        { year: '2018', title: 'Growth', state: 'Allocated', tone: 'green' },
        { year: '2020', title: 'Crash', state: 'Moved to Cash', tone: 'red' },
        { year: '2021', title: 'Recovery', state: 'Re-allocated', tone: 'green' },
        { year: '2022', title: 'Inflation Shock', state: 'Reduced', tone: 'red' },
        { year: '2023-2024', title: 'New Regime', state: 'Re-allocated', tone: 'green' },
        { year: '2025-Now', title: 'Current', state: 'Allocated', tone: 'green' },
      ],
    },
  },
  system: {
    eyebrow: '4. The System - Current View',
    headline: 'This is the current system view - updated live.',
    conditions: [
      {
        title: 'Momentum',
        value: '0.72',
        label: 'Positive trend',
        interpretation: 'Strengthening',
        window: 'last 30d',
        outcome: 'Pass',
        score: 72,
      },
      {
        title: 'Macro Regime',
        value: '0.61',
        label: 'Improving',
        interpretation: 'Improving',
        window: 'last 30d',
        outcome: 'Pass',
        score: 61,
      },
      {
        title: 'Volatility',
        value: '-0.28',
        label: 'Contained',
        interpretation: 'Compression intact',
        window: 'last 30d',
        outcome: 'Pass',
        score: 52,
      },
      {
        title: 'Market Breadth',
        value: '0.48',
        label: 'Healthy',
        interpretation: 'Mixed, constructive',
        window: 'last 30d',
        outcome: 'Scaled',
        score: 64,
      },
      {
        title: 'Liquidity',
        value: '0.22',
        label: 'Adequate',
        interpretation: 'Stable',
        window: 'last 30d',
        outcome: 'Pass',
        score: 55,
      },
    ],
    logic: [
      { label: 'Momentum is positive and accelerating', status: 'Pass' },
      { label: 'Macro regime is improving', status: 'Pass' },
      { label: 'Volatility is contained', status: 'Pass' },
      { label: 'Market breadth is healthy', status: 'Scaled' },
      { label: 'Liquidity is adequate', status: 'Pass' },
    ],
    resultCopy: 'Conditions are constructive for maintained exposure.',
    result: 'Allocated (80%)',
    cta: {
      title: 'See where these readings place the market',
      body: 'Explore the full condition space and regime analysis.',
      label: 'View full condition space',
      href: '/methodology',
    },
  },
  access: {
    eyebrow: '5. Access',
    headline: 'Get access to the current signal.',
    subhead: 'Simple pricing. Cancel anytime.',
    price: '€49',
    period: '/month',
    benefits: [
      'Live signal updates daily',
      'Full system view',
      'Historical signal record',
      'Email updates & alerts',
    ],
    cta: { label: 'Get access', href: '/sign-up' },
    included: [
      {
        title: 'The daily market exposure signal',
        body: 'Know how much exposure to hold.',
      },
      {
        title: 'The full system view',
        body: 'See all conditions, logic, and regime position.',
      },
      {
        title: 'Historical signal record',
        body: 'Review how the system performed across market cycles.',
      },
      {
        title: 'Updates & alerts',
        body: 'Stay informed with daily updates after market close.',
      },
    ],
  },
}

export type HomepageContent = typeof homepageContent
